# Generated by Django 3.2.7 on 2021-09-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='date de mise a jour')),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=10)),
                ('lieu', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
