# Generated by Django 2.2.24 on 2021-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Resolve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_mise_a_jour',
            field=models.DateField(verbose_name='date de mise a jour'),
        ),
    ]
