# Generated by Django 3.2.7 on 2021-10-22 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Resolve', '0002_alter_personne_date_mise_a_jour'),
        ('Resolve', '0002_auto_20210910_1307'),
    ]

    operations = [
    ]
