# Generated by Django 3.2.7 on 2021-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Resolve', '0003_merge_20211022_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_mise_a_jour',
            field=models.DateField(auto_now_add=True, verbose_name='Date inscription '),
        ),
    ]
